---
title: "Project proposal"
author: "XEM Team"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r load-packages, message = FALSE, echo = FALSE }
library(tidyverse)
library(broom)
library(here)
library(dplyr)
library(ggplot2)
library(ggridges)
library(forcats)
library(scales)
library(skimr)
library(rsample)
library(tidypredict)
library(tidymodels)
library(knitr)
```

```{r load-data, include=FALSE}
titanic <- read.csv(here::here("data/titanic.csv"))
```

turning survived into factor variable
```{r survived-factor}
titanic <- titanic %>%
  mutate(Survived = factor(Survived)) 
  mutate(Pclass = factor(Pclass))

```

```{r}
titanic_age_na <- titanic %>%
  filter(!is.na(Age))
```
splitting data 
```{r titanic-splitting}
set.seed(1116)
titanic_split <- initial_split(titanic_age_na, prop = 0.80)
train_data <- training(titanic_split)
test_data  <- testing(titanic_split)
```

build recipe
``` {r titanic-recipe}
titanic_rec <- recipe(Survived ~ ., data = titanic) %>%
  # PassengerId isn't predictor, but keep around to ID
  update_role(PassengerId, new_role = "ID") %>%
  # remove name and cabin
  step_rm(Name, Ticket, Cabin, SibSp, Parch, Fare, Embarked) %>%
  # remove NAs for step cut to work
  step_filter(!is.na(Age)) %>%
  # discretise age variable
  step_cut(Age, breaks = c(0, 6, 18, 54)) %>%
  # make dummy variables 
  step_dummy(all_nominal(), -all_outcomes()) %>%
  # remove zero variance predictors
  step_zv(all_predictors())
```

define model
```{r titanic-model}
titanic_mod <- logistic_reg() %>% 
  set_engine("glm")
```
define workflow
```{r titanic-workflow}
titanic_wflow <- workflow() %>% 
  add_model(titanic_mod) %>% 
  add_recipe(titanic_rec)
```
fit model to training data
```{r titanic-fit-to-train}
titanic_fit <- titanic_wflow %>% 
  fit(data = train_data)
tidy(titanic_fit)
```

predict test data
```{r titanic-predict-test-data}
 titanic_pred <-predict(titanic_fit, test_data, type = "prob") %>%
  bind_cols(test_data %>% select(Survived, PassengerId)) 
titanic_pred
```


roc curve
``` {r titanic-roc-curve}
titanic_pred %>%
  roc_curve(truth = Survived, .pred_1, event_level = "second") %>%
  autoplot()
```

cutoff probability
```{r cutoff-prob}
cutoff_prob <- 0.6
titanic_pred %>%
  mutate(
    Survived      = if_else(Survived == 1, "Survived", "Not survived"),
    titanic_pred  = if_else(.pred_1 > cutoff_prob, "Predicted to survive", "predicted not to survive")
    ) %>%
  count(titanic_pred, Survived) %>%
  pivot_wider(names_from = Survived, values_from = n) %>%
  kable(col.names = c("", "Not Survived", "Survived"))
```

r squared and rmse
```{r rsq-rmse}
rsq(titanic_pred, truth = as.numeric(Survived), estimate = .pred_1)
rmse(titanic_pred, truth = as.numeric(Survived), estimate = .pred_1)
```


